### PR TITLE
add DOH3

### PR DESCRIPTION
**Pull request by hellodword**
https://github.com/AdguardTeam/AdGuardHome/issues/3955

As a debug tool, we can just implement it without waiting for the upstream :)

### CODE REVIEW

**Comment by ameshkov** [comment]
Hmm, I just don't think this is the right place to add this.

Would you mind the H3 implementation here instead:
https://github.com/AdguardTeam/dnsproxy/tree/master/upstream

It then can be quickly added to `dnslookup` as well.

**Comment by hellodword** [comment]
But https://github.com/AdguardTeam/AdGuardHome/issues/3955#issuecomment-997836595 shows that AdguardTeam is waiting for the Go standard library, and the Go standard library will [not](https://github.com/golang/go/issues/32204) implement it very soon.

**Comment by hellodword** [comment]
So in my opinion, as a debug tool, dnslookup could provide a simple one without waiting for all the upstreams(AdguardTeam and go team).

Once they get an implementation, dnslookup can easyly switch to them, because dnslookup is not a library, it's a cli tool, this means no breaking change at all.

**Comment by ameshkov** [comment]
I think if we implement it as an experiment with "additional" scheme `h3`, this won't hurt.

**Pull request closed without merging**
